site :opscode

cookbook 'apt'

# cookbook 'ruby'
# cookbook 'rake'


# cookbook 'python-software-properties', path:'site-cookbooks/python-software-properties'
# cookbook 'tex', path:'site-cookbooks/tex'
# cookbook 'emacs', path:'site-cookbooks/emacs'
# cookbook 'nkf', path:'site-cookbooks/nkf'
# cookbook 'jed', path:'site-cookbooks/jed'
# cookbook 'ess', path:'site-cookbooks/ess'
# cookbook 'git', path:'site-cookbooks/git'
# cookbook 'sqlite3', path:'site-cookbooks/sqlite3'
# cookbook 'libsqlite3-0', path:'site-cookbooks/libsqlite3-0'

# cookbook 'fastx-toolkit', path:'site-cookbooks/fastx-toolkit'
# cookbook 'bedtools', path:'site-cookbooks/bedtools'
# cookbook 'samtools', path:'site-cookbooks/samtools'

# cookbook 'cufflinks', path:'site-cookbooks/cufflinks'
# cookbook 'r-base', path:'site-cookbooks/r-base'
# cookbook 'r-base-dev', path:'site-cookbooks/r-base-dev'
# cookbook 'r-bioc-biobase', path:'site-cookbooks/r-bioc-biobase'
# cookbook 'r-bioc-cummerbund', path:'site-cookbooks/r-bioc-cummerbund'
# cookbook 'runit', path:'site-cookbooks/runit'

# cookbook 'gbrowse', path:'site-cookbooks/gbrowse'
# cookbook 'galaxy', path:'site-cookbooks/galaxy'
# cookbook 'torque-server', path:'site-cookbooks/torque-server'
# cookbook 'emboss', path:'site-cookbooks/emboss'
